# wrangler.toml

name = "scalar-plasma"
type = "pages"

[env.production]
routes = [
  { pattern = "macachor.org/*", zone_name = "macachor.org" }
]

[build]
command = "echo 'No build needed'"
cwd = "/"
